[package]
name = "bevy-genetic-particles"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9.1"
bevy_ecs = "0.9.1"
bevy_prototype_lyon = "0.7.2"
bevy_tasks = "0.9.1"
rand = "0.8.5"

[workspace]
resolver = "2"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
